### PR TITLE
fix: OPDS browser OOM

### LINKED ISSUE #385: OPDS Navigation crashes with many items
### Affected Version

0.14

### Describe the Bug

No problem with _small_ folders, but big folders result in crash. Start happenings when downloaded XML exceeds 30K in size

### Steps to Reproduce

1. configure a CWA instance
2. setup url in crossover settings
3. open Calibre Library in crossover main menu
4. open a folder with many books (like 50 entries)
5. crossover crashes

### Expected Behavior

book list in shown

### Relevant Log Output/Screenshots

```shell
[RX:'\nabort() was called at PC 0x420e5f51 on core 0\r\nCore  0 register dump:\r\nMEPC    : 0x4038242a  RA      : 0x403879e6  SP      : 0'] 
abort() was called at PC 0x420e5f51 on core 0
Core  0 register dump:
MEPC    : 0x4038242a  RA      : 0x403879e6  SP      : 0 [RX:'x'] x [RX:'3fcaf070  GP      : 0x3fc8ee00  \r\nTP      : 0x3f7ef098  T0     '] 3fcaf070  GP      : 0x3fc8ee00  
TP      : 0x3f7ef098  T0      [RX:' ']   [RX:': 0x37363534  T1      : 0x7271706f  T2      : 0x33323130  \r\nS0/'] : 0x37363534  T1      : 0x7271706f  T2      : 0x33323130  
S0/ [RX:'F'] F [RX:'P   : 0x3fcaf09c  S1      : 0x3fcaf09c  A0      : 0x3fcaf0a8  A'] P   : 0x3fcaf09c  S1      : 0x3fcaf09c  A0      : 0x3fcaf0a8  A [RX:'1'] 1 [RX:'      : 0x3fcaf08a  \r\nA2      : 0x00000000  A3      : 0x3fcaf0d']       : 0x3fcaf08a  
A2      : 0x00000000  A3      : 0x3fcaf0d [RX:'5'] 5 [RX:'  A4      : 0x00000001  A5      : 0x3fca7000  \r\nA6      : 0x7a7']   A4      : 0x00000001  A5      : 0x3fca7000  
A6      : 0x7a7 [RX:'9'] 9 [RX:'7877  A7      : 0x76757473  S2      : 0x000090e8  S3      : 0x3'] 7877  A7      : 0x76757473  S2      : 0x000090e8  S3      : 0x3 [RX:'f'] f [RX:'cca3a0  \r\nS4      : 0x00000000  S5      : 0x00000000  S6      :'] cca3a0  
S4      : 0x00000000  S5      : 0x00000000  S6      : [RX:' ']   [RX:'0x3fcca3a0  S7      : 0x000090e8  \r\nS8      : 0x000090e8  S9   '] 0x3fcca3a0  S7      : 0x000090e8  
S8      : 0x000090e8  S9    [RX:' ']   [RX:'  : 0x00000000  S10     : 0x00000000  S11     : 0x00000000  \r\nT']   : 0x00000000  S10     : 0x00000000  S11     : 0x00000000  
T [RX:'3'] 3 [RX:'      : 0x6e6d6c6b  T4      : 0x6a696867  T5      : 0x66656463 ']       : 0x6e6d6c6b  T4      : 0x6a696867  T5      : 0x66656463  [RX:' ']   [RX:'T6      : 0x62613938  \r\nMSTATUS : 0x00001801  MTVEC   : 0x40380'] T6      : 0x62613938  
MSTATUS : 0x00001801  MTVEC   : 0x40380 [RX:'0'] 0 [RX:'01  MCAUSE  : 0x00000007  MTVAL   : 0x00000000  \r\nMHARTID : 0x0'] 01  MCAUSE  : 0x00000007  MTVAL   : 0x00000000  
MHARTID : 0x0 [RX:'0'] 0 [RX:'000000  \r\n\r\nStack memory:\r\n3fcaf070: 0x3f7ef098 0x4210a99a 0x3f'] 000000  

Stack memory:
3fcaf070: 0x3f7ef098 0x4210a99a 0x3f [RX:'c'] c [RX:'af088 0x4038cfb4 0x4038cf30 0x00000000 0x00000030 0x3fc91ad0\r\n3'] af088 0x4038cfb4 0x4038cf30 0x00000000 0x00000030 0x3fc91ad0
3 [RX:'f'] f [RX:'caf090: 0x3fcaf09c 0x3fc91aec 0x3fcaf088 0x65303234 0x31356635 '] caf090: 0x3fcaf09c 0x3fc91aec 0x3fcaf088 0x65303234 0x31356635  [RX:'0'] 0 [RX:'x00000000 0x726f6261 0x20292874\r\n3fcaf0b0: 0x20736177 0x6c6c616'] x00000000 0x726f6261 0x20292874
3fcaf0b0: 0x20736177 0x6c6c616 [RX:'3'] 3 [RX:' 0x61206465 0x43502074 0x34783020 0x35653032 0x20313566 0x63206']  0x61206465 0x43502074 0x34783020 0x35653032 0x20313566 0x63206 [RX:'e'] e [RX:'6f\r\n3fcaf0d0: 0x2065726f 0x00000030 0x00000000 0x3101adc2 0x000'] 6f
3fcaf0d0: 0x2065726f 0x00000030 0x00000000 0x3101adc2 0x000 [RX:'0'] 0 [RX:'0000 0x00000000 0x3fcc85f8 0x420e5f54\r\n3fcaf0f0: 0x3fcca3a0 0x0'] 0000 0x00000000 0x3fcc85f8 0x420e5f54
3fcaf0f0: 0x3fcca3a0 0x0 [RX:'0'] 0 [RX:'000000 0x3fcc85f8 0x3fca7690 0x000090e8 0x00000000 0x3fcc85f8 0'] 000000 0x3fcc85f8 0x3fca7690 0x000090e8 0x00000000 0x3fcc85f8 0 [RX:'x'] x [RX:'420e5fb6\r\n3fcaf110: 0x3fcc85f8 0x00000000 0x3fcc85f8 0x420e555a'] 420e5fb6
3fcaf110: 0x3fcc85f8 0x00000000 0x3fcc85f8 0x420e555a [RX:' ']   [RX:'0x000090e8 0x00000000 0x420f6c70 0x3c5ef424\r\n3fcaf130: 0x000090'] 0x000090e8 0x00000000 0x420f6c70 0x3c5ef424
3fcaf130: 0x000090 [RX:'e'] e [RX:'8 0x00000000 0x000090e9 0x420e590a 0x3fca7000 0x3fca7128 0x3fca'] 8 0x00000000 0x000090e9 0x420e590a 0x3fca7000 0x3fca7128 0x3fca [RX:'f'] f [RX:'2f0 0x420e737c\r\n3fcaf150: 0x3fca7000 0x3c5ec000 0x3c5d3018 0x00'] 2f0 0x420e737c
3fcaf150: 0x3fca7000 0x3c5ec000 0x3c5d3018 0x00 [RX:'0'] 0 [RX:'090e8 0x00000000 0x00000000 0x3fcaf2f0 0x3fcca3a0\r\n3fcaf170: 0x'] 090e8 0x00000000 0x00000000 0x3fcaf2f0 0x3fcca3a0
3fcaf170: 0x [RX:'3'] 3 [RX:'fcaf2f8 0x000090e8 0x00000000 0x420e7856 0x00000000 0x00000000 '] fcaf2f8 0x000090e8 0x00000000 0x420e7856 0x00000000 0x00000000  [RX:'0'] 0 [RX:'x00000000 0x00000000\r\n3fcaf190: 0x000927c0 0x3fca7128 0x3fca700'] x00000000 0x00000000
3fcaf190: 0x000927c0 0x3fca7128 0x3fca700 [RX:'0'] 0 [RX:' 0x3fcaf2d8 0x3fcaf2f0 0x000000c8 0x3fca0000 0x42019b92\r\n3fcaf1']  0x3fcaf2d8 0x3fcaf2f0 0x000000c8 0x3fca0000 0x42019b92
3fcaf1 [RX:'b'] b [RX:'0: 0x3fc8e668 0x3fca72d8 0x3fcbccb0 0x00000000 0x00000000 0x000'] 0: 0x3fc8e668 0x3fca72d8 0x3fcbccb0 0x00000000 0x00000000 0x000 [RX:'0'] 0 [RX:'0000 0x0a000000 0x3fcca3a0\r\n3fcaf1d0: 0x000090ef 0x000090e8 0x0'] 0000 0x0a000000 0x3fcca3a0
3fcaf1d0: 0x000090ef 0x000090e8 0x0 [RX:'0'] 0 [RX:'001800 0x00000000 0x00000000 0x3fcbccb0 0x3fcb157c 0x0000001f\r\n'] 001800 0x00000000 0x00000000 0x3fcbccb0 0x3fcb157c 0x0000001f
 [RX:'3'] 3 [RX:'fcaf1f0: 0x00000015 0x00cbcca8 0x3fca01bb 0x00001388 0x1388f901'] fcaf1f0: 0x00000015 0x00cbcca8 0x3fca01bb 0x00001388 0x1388f901 [RX:' ']   [RX:'0x3fcb0100 0x64706f2f 0x68732f73\r\n3fcaf210: 0x2f666c65 0x8d0000'] 0x3fcb0100 0x64706f2f 0x68732f73
3fcaf210: 0x2f666c65 0x8d0000 [RX:'3'] 3 [RX:'1 0x70747468 0x00000073 0x00000000 0x85000030 0x00000000 0x0000'] 1 0x70747468 0x00000073 0x00000000 0x85000030 0x00000000 0x0000 [RX:'0'] 0 [RX:'000\r\n3fcaf230: 0x00000000 0x80ca7128 0x3fcbcdd0 0x0000000f 0x00'] 000
3fcaf230: 0x00000000 0x80ca7128 0x3fcbcdd0 0x0000000f 0x00 [RX:'0'] 0 [RX:'0000f 0x44504f5b 0x3fcab59c 0x0000001f\r\n3fcaf250: 0x00000018 0x'] 0000f 0x44504f5b 0x3fcab59c 0x0000001f
3fcaf250: 0x00000018 0x [RX:'0'] 0 [RX:'0746820 0x69736142 0x00000063 0x00000000 0x85617261 0x00000000 '] 0746820 0x69736142 0x00000063 0x00000000 0x85617261 0x00000000  [RX:'0'] 0 [RX:'x00000000\r\n3fcaf270: 0x000000c8 0x000090e8 0x006f6901 0x0000000'] x00000000
3fcaf270: 0x000000c8 0x000090e8 0x006f6901 0x0000000 [RX:'1'] 1 [RX:' 0x0009000a 0x00000000 0x00000000 0x00000000\r\n3fcaf290: 0x80000']  0x0009000a 0x00000000 0x00000000 0x00000000
3fcaf290: 0x80000 [RX:'0'] 0 [RX:'00 0x00000000 0x00000000 0x3101adc2 0x00000000 0x3fcbc368 0x000'] 00 0x00000000 0x00000000 0x3101adc2 0x00000000 0x3fcbc368 0x000 [RX:'0'] 0 [RX:'b9b2 0x00000000\r\n3fcaf2b0: 0x00000000 0x3fca7000 0x3fcab2d0 0x4'] b9b2 0x00000000
3fcaf2b0: 0x00000000 0x3fca7000 0x3fcab2d0 0x4 [RX:'2'] 2 [RX:'003b12 0x400391e6 0x00000001 0x3fcafaac 0x3fcab320\r\n3fcaf2d0: 0'] 003b12 0x400391e6 0x00000001 0x3fcafaac 0x3fcab320
3fcaf2d0: 0 [RX:'x'] x [RX:'00000000 0x00000000 0x3fcbcc3c 0x0000003d 0x00000060 0x3fca8000'] 00000000 0x00000000 0x3fcbcc3c 0x0000003d 0x00000060 0x3fca8000 [RX:' ']   [RX:'0xc0380000 0x00000015\r\n3fcaf2f0: 0x3fcaf2f8 0x00000000 0x3fca83'] 0xc0380000 0x00000015
3fcaf2f0: 0x3fcaf2f8 0x00000000 0x3fca83 [RX:'0'] 0 [RX:'0 0x4038cb18 0x00000000 0x00000000 0x3fcbc368 0x00000030\r\n3fcaf'] 0 0x4038cb18 0x00000000 0x00000000 0x3fcbc368 0x00000030
3fcaf [RX:'3'] 3 [RX:'10: 0x00000030 0x00000000 0x00000011 0x4038ccb2 0x00000011 0x3f'] 10: 0x00000030 0x00000000 0x00000011 0x4038ccb2 0x00000011 0x3f [RX:'c'] c [RX:'a86b8 0x00001800 0x403828aa\r\n3fcaf330: 0x000927c0 0x3fca7128 0x'] a86b8 0x00001800 0x403828aa
3fcaf330: 0x000927c0 0x3fca7128 0x [RX:'0'] 0 [RX:'000b9b2 0x00000000 0x3fcbcea4 0x3fcbccec 0x3fca8300 0x4038cad2\r'] 000b9b2 0x00000000 0 [RX:'\n'] x3fcbccec 0x3fca8300 0x4038cad2
 [RX:'3fcaf350: 0x3fcbcea4 0x3fcbccf4 0x3fca8300 0x4038cc26 0x3fcbc34'] 3fcaf350: 0x3fcbcea4 0x3fcbccf4 0x3fca8300 0x4038cc26 0x3fcbc34 [RX:'8'] 8 [RX:' 0x3fcbcea4 0x3fcbcfd0 0x42003574\r\n3fcaf370: 0x3f7ef098 0x4212f']  0x3fcbcea4 0x3fcbcfd0 0x42003574
3fcaf370: 0x3f7ef098 0x4212f [RX:'e'] e [RX:'9e 0x00000000 0x3fcbd034 0x000927c0 0x3fca7128 0x3fcab308 0x420'] 9e 0x00000000 0x3fcbd034 0x000927c0 0x3fca7128 0x3fcab308 0x420 [RX:'0'] 0 [RX:'359c\r\n3fcaf390: 0x3fcbcea4 0x3fcab320 0x3fcab2d0 0x3101adc2 0x0'] 359c
3fcaf390: 0x3fcbcea4 0x3fcab320 0x3fcab2d0 0x3101adc2 0x0 [RX:'0'] 0 [RX:'000000 0x00000064 0x3fcab2d0 0x42003ffe\r\n3fcaf3b0: 0x00000000 0'] 000000 0x00000064 0x3fcab2d0 0x42003ffe
3fcaf3b0: 0x00000000 0 [RX:'x'] x [RX:'00000001 0x600c0000 0x4201d780 0xfa000000 0x0000b9b2 0x3fc9e200'] 00000001 0x600c0000 0x4201d780 0xfa000000 0x0000b9b2 0x3fc9e200 [RX:' ']   [RX:'0x0000b9b2\r\n3fcaf3d0: 0x3fca0000 0x3fca716c 0x3fc9e000 0x420147'] 0x0000b9b2
3fcaf3d0: 0x3fca0000 0x3fca716c 0x3fc9e000 0x420147 [RX:'9'] 9 [RX:'0 0x00000000 0x00000000 0x00000000 0x42044ab2\r\n3fcaf3f0: 0x0000'] 0 0x00000000 0x00000000 0x00000000 0x42044ab2
3fcaf3f0: 0x0000 [RX:'0'] 0 [RX:'000 0x00000000 0x00000000 0x00000000 0x00000000 0x3fca7000 0x00'] 000 0x00000000 0x00000000 0x00000000 0x00000000 0x3fca7000 0x00 [RX:'0'] 0 [RX:'00000 0x420461d8\r\n3fcaf410: 0x00000000 0x00000000 0x00000000 0x'] 00000 0x420461d8
3fcaf410: 0x00000000 0x00000000 0x00000000 0x [RX:'4'] 4 [RX:'038a5fc 0x00000000 0x00000000 0x00000000 0x00000000\r\n3fcaf430: '] 038a5fc 0x00000000 0x00000000 0x00000000 0x00000000
3fcaf430:  [RX:'0'] 0 [RX:'x00000000 0xa5a5a5a5 0xa5a5a5a5 0xa5a5a5a5 0xa5a5a5a5 0xa5a5a5a'] x00000000 0xa5a5a5a5 0xa5a5a5a5 0xa5a5a5a5 0xa5a5a5a5 0xa5a5a5a [RX:'5'] 5 [RX:' 0xbaad5678 0x00000160\r\n3fcaf450: 0xabba1234 0x00000154 0x3fcaf']  0xbaad5678 0x00000160
3fcaf450: 0xabba1234 0x00000154 0x3fcaf [RX:'0'] 0 [RX:'60 0x0000c642 0x3fca1534 0x3fca1534 0x3fcaf458 0x3fca152c\r\n\r\n\r\n'] 60 0x0000c642 0x3fca1534 0x3fca1534 0x3fcaf458 0x3fca152c


 [RX:'\nELF file SHA256: 734ce7059ce1e60e\r\n\r\nRebooting...\r\nESP-ROM:esp'] 
ELF file SHA256: 734ce7059ce1e60e

Rebooting...
```

### PR DESCRIPTION
**Pull request by KasyanDiGris**
## Summary

- Rewrite OpdsParser to stream parsing instead of full content
- Fix OOM due to big http xml response

Closes #385 

---

### AI Usage

While CrossPoint doesn't have restrictions on AI tools in contributing, please be transparent about their usage as it 
helps set the right context for reviewers.

Did you use AI tools to help write this code? _**NO**_

### CODE REVIEW

**Comment by KasyanDiGris** [comment]
@daveallie Can you please review PR?

File: lib/OpdsParser/OpdsParser.h [hunk 1]
```diff
@@ -44,26 +44,23 @@ using OpdsBook = OpdsEntry;
...
   OpdsParser& operator=(const OpdsParser&) = delete;
 
-  /**
-   * Parse an OPDS XML feed.
-   * @param xmlData Pointer to the XML data
-   * @param length Length of the XML data
-   * @return true if parsing succeeded, false on error
-   */
-  bool parse(const char* xmlData, size_t length);
+  void push(const char* xmlData, size_t length);
```
Comment (daveallie) [inline lib/OpdsParser/OpdsParser.h]: Instead of this push method, and a completely separate `OpdsStream` class, let's subclass `OpdsParser` off `Print` (like we do for `ContentOpfParser`) and then implement `write` directly in this class.

File: lib/OpdsParser/OpdsParser.h [hunk 2]
```diff
@@ -42,28 +43,30 @@ using OpdsBook = OpdsEntry;
  *     }
  *   }
  */
-class OpdsParser {
+class OpdsParser final : public Print {
```
Comment (daveallie) [inline lib/OpdsParser/OpdsParser.h:46]: Do you think it's worthwhile to go all the way and just subclass Stream? Including the stubs for `available`, `peek`, and `read` in here?

Comment (KasyanDiGris) [reply lib/OpdsParser/OpdsParser.h:46]: I think there is a mistake in the HttpClient library, because the implementation of the `writeToStream` method requires the `Printer` class, not the `Stream` class. But I don't want to make patches.
In addition, all other parsers are subclasses of `Printer`, and that's right, because they're all designed to be write-only streams.
