### PR TITLE
fix: Account for `nbsp;` character as non-breaking space

### LINKED ISSUE #743: Single-character prepositions merge with following words in some EPUB files
### Affected Version

0.16.0

### Describe the Bug

In some EPUB files (tested only 3 files, issue appears in 1), single-character Polish prepositions (i, w, z) incorrectly merge with the following word, creating malformed text.

Examples
- "znami" instead of "z nami" (with us)
- "wdomu" instead of "w domu" (at home)
- "ifioletową" instead of "i fioletową" (and purple)
- "iwmiejscu" instead of "i w miejscu" (and in place)

Additional context
- **The same EPUB file displays correctly on other readers:**
  - FBReader (iPhone)
  - Calibre (macOS)

- The issue does NOT appear to be affected by:
  - Text justification settings
  - Hyphenation settings
- Multiple prepositions can be affected in sequence (e.g., "i w" → "iw")

### Steps to Reproduce

Open an affected Polish-language EPUB file and observe merged prepositions throughout the text.

### Expected Behavior

Single-character prepositions should be separated from following words by a space.
Examples
- "z nami" instead of "znami"  (with us)
- "w domu" instead of "wdomu" (at home)
- "i fioletową" instead of "ifioletową" (and purple)
- "i w miejscu" instead of "iwmiejscu" (and in place)

### Relevant Log Output/Screenshots

```shell

```

### PR DESCRIPTION
**Pull request by jdk2pq**
## Summary

Closes #743.

**What is the goal of this PR?**

- Add back handling for HTML entities in expat. This was originally part of the code that got removed [here](https://github.com/crosspoint-reader/crosspoint-reader/pull/274)
- Handle `&nbsp;` characters to resolve issue #743 

**What changes are included?**

- Brought back HTML entity table from previous commit and refactored it to use a static const char * table with linear lookup to reduce heap allocations.
- Used `XML_SetDefaultHandlerExpand` in expat to parse out the entities correctly, without needing them defined in DOCTYPE
- Added handling for `&nbsp;` so that the text stays together and doesn't break onto a new line with text separated by an `&nbsp;`

## Additional Context

- This supersedes [this PR](https://github.com/crosspoint-reader/crosspoint-reader/pull/751) that simply handled `nbsp;` as whitespace. Instead, we want that character to serve its true purpose and affect the line-breaking algorithm.
- Updated my test EPUB [here](https://github.com/jdk2pq/css-test-epub) with `&nbsp;` characters examples at the end of the book

---

### AI Usage

While CrossPoint doesn't have restrictions on AI tools in contributing, please be transparent about their usage as it 
helps set the right context for reviewers.

Did you use AI tools to help write this code? _**YES**_, Claude Code

### CODE REVIEW

**Comment by lukestein** [comment]
Looks good on my books but I'd love if @IjonFryderyk can test or else share an ebook file that caused his problem so we can check.

**Review by osteotek — DISMISSED** [review]

**Comment by IjonFryderyk** [comment]
Is there a way to test this locally without flashing to my X4? Sorry, I'm a noob with embedded development - not sure if that's possible with ESP32 firmware.

**Comment by jdk2pq** [comment]
> Is there a way to test this locally without flashing to my X4? Sorry, I'm a noob with embedded development - not sure if that's possible with ESP32 firmware.

It's all good! Currently, there isn't a great way of testing CrossPoint without flashing on-device. There's some steps being taken in other PRs/forks to create an emulated testing environment, but they're still works in progress and a bit limited right now.

If you're comfortable with flashing a new firmware, you can download the `firmware.bin` artifact from [here](https://github.com/crosspoint-reader/crosspoint-reader/actions/runs/21810347593?pr=757) and flash it with the flash tool found [here](https://xteink.dve.al/), with a fair warning that I would still consider this "pre-release" code, and it may contain bugs (though I've tested it thoroughly on my device, and all's working well from what I can tell).

**Comment by IjonFryderyk** [comment]
Here's an EPUB file that contains `nbsp;` and triggers the bug: 
https://www.dropbox.com/scl/fi/sv2nocxmh1ry9nccdcjo4/Ja_to_ktos_inny_Septologia_3-5.epub?rlkey=7vvappc58nffscrx7e2yu7dwi&dl=0

**Comment by osteotek** [comment]
I've tested this on provided polish epub, and words including nbsp are still merged together
image

**Comment by jdk2pq** [comment]
@osteotek @IjonFryderyk I've just pushed up a new commit that I've thoroughly tested with the Polish EPUB and my own test EPUBs. Let me know if this does the trick to fix things!

@daveallie I followed your suggestion of bringing back the HTML entity parsing code, and I made some minor changes to reduce heap allocations, since I was hitting heap issues when loading the Polish EPUB (chapters are ~200+ pages on my device, and it would hit an error when it was processing all the chapter's pages at the beginning of a cacheless load).

File: lib/Epub/Epub/htmlEntities.cpp [hunk 1]
```diff
@@ -0,0 +1,183 @@
...
+    {"&Sigma;", "Σ"},  {"&Tau;", "Τ"},     {"&Upsilon;", "Υ"},     {"&Phi;", "Φ"},    {"&Chi;", "Χ"},
+    {"&Psi;", "Ψ"},    {"&Omega;", "Ω"},   {"&alpha;", "α"},       {"&beta;", "β"},   {"&gamma;", "γ"},
+    {"&delta;", "δ"},  {"&epsilon;", "ε"}, {"&zeta;", "ζ"},        {"&eta;", "η"},    {"&theta;", "θ"},
+    {"&iota;", "ι"},   {"&kappa;", "κ"},   {"&lambda;", "λ"},      {"&mu;", "μ"},     {"&nu;", "ν"},
+    {"&xi;", "ξ"},     {"&omicron;", "ο"}, {"&pi;", "π"},          {"&rho;", "ρ"},    {"&sigmaf;", "ς"},
+    {"&sigma;", "σ"},  {"&tau;", "τ"},     {"&upsilon;", "υ"},     {"&phi;", "φ"},    {"&chi;", "χ"},
+    {"&psi;", "ψ"},    {"&omega;", "ω"},   {"&thetasym;", "ϑ"},    {"&upsih;", "ϒ"},  {"&piv;", "ϖ"},
+    {"&OElig;", "Œ"},  {"&oelig;", "œ"},   {"&Scaron;", "Š"},      {"&scaron;", "š"}, {"&Yuml;", "Ÿ"},
+    {"&fnof;", "ƒ"},   {"&circ;", "ˆ"},    {"&tilde;", "˜"},       {"&ensp;", ""},    {"&emsp;", ""},
+    {"&thinsp;", ""},  {"&zwnj;", "‌"},  {"&zwj;", "‍"},       {"&lrm;", "‎"},  {"&rlm;", "‏"},
```
[the remark this answers is not in the document]
Comment (osteotek) [reply lib/Epub/Epub/htmlEntities.cpp]: `&emsp;` and `&ensp;` probably can be mapped to just space

**Comment by osteotek** [comment]
@jdk2pq I've tested this on the polish epub, seems to be working good, thank you. Some of the Copilot suggestions seems valid to me, but ultimately up to if you want to address them

File: lib/Epub/Epub/parsers/ChapterHtmlSlimParser.cpp [hunk 2]
```diff
@@ -393,6 +416,22 @@ void XMLCALL ChapterHtmlSlimParser::characterData(void* userData, const XML_Char
...
+    if (utf8Value != nullptr) {
+      // Known entity: expand to its UTF-8 value
+      characterData(userData, utf8Value, strlen(utf8Value));
+      return;
+    }
+    // Unknown entity: preserve original &...; sequence
+    characterData(userData, s, len);
+    return;
+  }
+  // Not an entity we recognize - skip it
```
Comment (jdk2pq) [inline lib/Epub/Epub/parsers/ChapterHtmlSlimParser.cpp:432]: Though Copilot wanted this to pass through all text, even if it was not an entity starting with `&` and ending with `;`, when I did that, it shows the full XML header at the top of chapters.

Image

 Instead, I just updated the comment to reflect that we skip it.

File: lib/Epub/Epub/htmlEntities.cpp
Comment (jdk2pq) [inline lib/Epub/Epub/htmlEntities.cpp:1]: Removed the unused code from this file, since we only really use the `ENTITY_LOOKUP` and accompanying function. Copilot was only complaining about the unused code.

Comment (jdk2pq) [reply lib/Epub/Epub/htmlEntities.cpp:1]: But I did update the em, en, and thin space lookups to correspond to their correct character instead of empty strings.

File: lib/Epub/Epub/htmlEntities.cpp [hunk 3]
```diff
@@ -0,0 +1,76 @@
...
+    {"&loz;", "◊"},    {"&spades;", "♠"},  {"&clubs;", "♣"},       {"&hearts;", "♥"}, {"&diams;", "♦"}};
+
+static const size_t ENTITY_LOOKUP_COUNT = sizeof(ENTITY_LOOKUP) / sizeof(ENTITY_LOOKUP[0]);
+
+// Lookup a single HTML entity and return its UTF-8 value
+const char* lookupHtmlEntity(const char* entity, int len) {
+  for (size_t i = 0; i < ENTITY_LOOKUP_COUNT; i++) {
+    const char* key = ENTITY_LOOKUP[i].key;
+    const size_t keyLen = strlen(key);
+    if (static_cast<size_t>(len) == keyLen && memcmp(entity, key, keyLen) == 0) {
```
Comment (ngxson) [inline lib/Epub/Epub/htmlEntities.cpp:70]: nits: maybe use `strncmp`

File: lib/Epub/Epub/htmlEntities.cpp [hunk 4]
```diff
@@ -0,0 +1,76 @@
...
+#include "htmlEntities.h"
+
+#include <cstring>
+
+struct EntityPair {
+  const char* key;
+  const char* value;
+};
+
+static const EntityPair ENTITY_LOOKUP[] = {
```
Comment (ngxson) [inline lib/Epub/Epub/htmlEntities.cpp:13]: possible improvement for future: maybe compile this list as a tree structure, to avoid linear search and save space

**Comment by jonasdiemer** [comment]
Merged, as the open topics can be done in future PRs.
