### PR TITLE
fix: back navigation from BMPViewer

### LINKED ISSUE #1553: BMPViewer incorrect back behavior
@Levrk @osteotek @CaptainFrito
Just loaded the CrossPoint release 1.2.0 rc. When I open the sleep image. The bmp image opens. Then the screen flashes 2-3 times. And then the image is shown.

now if I hit back button. Takes me to homepage. I have to navigate again to browse files and to sleep folder and open the second bmp image.

Is this intended behaviour?

i hope this is related to this merge
https://github.com/crosspoint-reader/crosspoint-reader/pull/887
rc release from here
https://github.com/crosspoint-reader/crosspoint-reader/pull/1483

### PR DESCRIPTION
**Pull request by Telemaniaka**
## Summary

This fixes navigating back from the BMP Viewer to the FileBrowser which was broken when moving to the new ActivityManager

This is fixed by making FileBrowserActivity able to take a full file path on enter and splitting the basePath and fileName from it and navigating to the correct place.

fixes: https://github.com/crosspoint-reader/crosspoint-reader/issues/1553

duplicates: https://github.com/crosspoint-reader/crosspoint-reader/pull/910 to some extend but mine has the file cursor at the correct file instead of the first one in the folder

## Additional Context

* Add any other information that might be helpful for the reviewer (e.g., performance implications, potential risks, 
  specific areas to focus on).

---

### AI Usage

While CrossPoint doesn't have restrictions on AI tools in contributing, please be transparent about their usage as it 
helps set the right context for reviewers.

Did you use AI tools to help write this code? _**PARTIALLY**_

### CODE REVIEW

**Review by znelson — DISMISSED** [review]
LTGM. Refactoring `ReaderActivity::extractFolderPath` into a shared util in perhaps `FsHelpers` could simplify.

**Comment by Telemaniaka** [comment]
Moved `extractFolderPath` from `ReaderActivity` to `FsHelpers`

File: src/activities/home/FileBrowserActivity.cpp [hunk 1]
```diff
@@ -108,9 +108,28 @@ void FileBrowserActivity::loadFiles() {
...
-  loadFiles();
   selectorIndex = 0;
 
+  auto root = Storage.open(basepath.c_str());
+  if (!root) {
+    basepath = "/";
+    loadFiles();
+  } else if (!root.isDirectory()) {
+    root.close();
+    lockLongPressBack = true;
```
Comment (Uri-Tauber) [inline src/activities/home/FileBrowserActivity.cpp]: This introduce a small regression: returning from BMP viewer make the first back press in fileBrowser do nothing.
the fix is to change this line to `lockLongPressBack = mappedInput.isPressed(MappedInputManager::Button::Back);`

Otherwise looks good. Thanks for your contribution.

**Review by Uri-Tauber — CHANGES_REQUESTED** [review]

File: src/activities/home/FileBrowserActivity.cpp (hunk 1 above)
Comment (Telemaniaka) [reply src/activities/home/FileBrowserActivity.cpp]: Thanks.

**Review by Uri-Tauber — APPROVED** [review]

**Review by znelson — APPROVED** [review]
